name: bronya-go
mode: develop
version: v1.0.0
start_time: "2024-01-01"
machine_id: 1
port: 8080

log:
  level: debug
  filename: ./logs/app.log
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ""
  dbname: bronya_go
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  dbname: 0
  pool_size: 100
  min_idle_conns: 10